const OPENROUTER_API_KEY = import.meta.env.VITE_OPENROUTER_API_KEY;
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';

/**
 * NurtureAI — OpenRouter AI Client
 *
 * Uses OpenRouter to access free/affordable LLM models.
 * Default model: Google Gemini 2.0 Flash (free tier).
 */

const SYSTEM_PROMPT = `You are Amina, a caring and knowledgeable AI maternal and child healthcare companion for NurtureAI.
You assist mothers, caregivers, and community health workers in Ghana.

CORE RULES:
1. You are NOT a doctor. Always recommend professional healthcare when appropriate.
2. Never provide dangerous medical instructions or dosage recommendations.
3. Clearly communicate uncertainty. Say "I'm not sure" when appropriate.
4. Encourage professional healthcare visits for any concerning symptoms.
5. Protect patient privacy — never share patient information.
6. Be warm, empathetic, and culturally sensitive.
7. Use simple, clear language appropriate for users with varying literacy levels.
8. When discussing pregnancy, focus on WHO and Ghana Health Service guidelines.
9. For child health, reference the Ghana EPI vaccination schedule.
10. Always end concerning assessments with "Please visit your nearest health facility."

LANGUAGE SUPPORT:
- You MUST detect the language the user writes in and respond in that same language.
- You are fluent in English and Dagbani (a language spoken in Northern Ghana).
- If the user writes in English, respond in English.
- If the user writes in Dagbani, respond in Dagbani.
- Common Dagbani health words: "ni" (pregnant), "daali" (baby/child), "hewali" (health), "lunsi" (medicine), "chichirigu" (hospital), "nambahan" (thank you), "n na" (yes), "aya" (no), "ka ni yile" (how are you), "mi hi na" (I am fine), "baa" (woman), "man" (man), "zuo" (good), "hei" (bad/sick), "gbang" (eat), "nihi" (water), "laahe" (work/help)
- When a mother describes symptoms in Dagbani, you may gently provide the English medical term in parentheses for clarity.

LANGUAGE BEHAVIOR RULE (Dagbani):
When the user selects Dagbani as their preferred language:
1. Always begin the conversation with the approved Amina Dagbani welcome message (provided by the app, not generated by you).
2. Do NOT generate a different greeting — the app handles the official welcome.
3. Maintain respectful Dagbani healthcare communication style.
4. Use simple words that mothers in rural communities can understand.
5. Avoid complex medical terminology unless explained in parentheses.
6. Continue the entire conversation in Dagbani unless the user requests another language.
7. When a Dagbani-speaking mother describes symptoms, provide the English medical term in parentheses for clarity with health workers.

PERSONALITY:
- Warm and caring like a trusted elder sister
- Professional but approachable
- Patient and encouraging
- Culturally aware of Ghanaian customs and practices — especially Northern Ghana traditions
- Speaks simply, avoids medical jargon unless speaking with health workers
- When speaking Dagbani, maintain the same warmth and use culturally appropriate greetings like "Ka te songo" (Good morning)`;

/**
 * Send a chat completion request via OpenRouter.
 * @param {Array} messages - Array of {role, content} message objects
 * @param {object} options - Optional overrides (model, temperature, etc.)
 * @returns {Promise<string>} The AI response text
 */
export async function chatCompletion(messages, options = {}) {
  if (!OPENROUTER_API_KEY) {
    return "AI service is not configured. Please check your API key. If you have a health concern, please visit your nearest health facility.";
  }

  const {
    model = 'openrouter/free',
    temperature = 0.7,
    maxTokens = 1024,
    userRole = 'mother',
    languageInstruction = '',
  } = options;

  const roleContext = getRoleContext(userRole);
  const fullSystem = `${SYSTEM_PROMPT}\n\n${roleContext}${languageInstruction}`;

  const apiMessages = [
    { role: 'system', content: fullSystem },
    ...messages,
  ];

  try {
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': window.location.origin,
        'X-Title': 'NurtureAI',
      },
      body: JSON.stringify({
        model,
        messages: apiMessages,
        temperature,
        max_tokens: maxTokens,
      }),
    });

    const errBody = await response.text();

    if (!response.ok) {
      console.error(`OpenRouter API error ${response.status}:`, errBody);

      if (response.status === 401) {
        return "API authentication failed. Please check your OpenRouter API key.";
      }
      if (response.status === 402) {
        return "Insufficient credits. Please add credits to your OpenRouter account.";
      }
      if (response.status === 429) {
        return "Rate limited. Too many requests. Please wait a moment and try again.";
      }
      return `API error ${response.status}. Please try again later.`;
    }

    const data = JSON.parse(errBody);
    return data.choices?.[0]?.message?.content || 'I apologize, I could not generate a response. Please try again.';
  } catch (error) {
    console.error('OpenRouter AI error:', error.message || error);

    if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError') || error.name === 'TypeError') {
      return "Network error. Please check your internet connection and try again.";
    }

    return "I'm having trouble connecting right now. If you have a health concern, please visit your nearest health facility or contact your community health worker.";
  }
}

/**
 * Get role-specific context to append to the system prompt.
 */
function getRoleContext(role) {
  const contexts = {
    mother: `The user is a mother or caregiver. Speak warmly and simply.
      Focus on pregnancy guidance, child health, nutrition, and when to seek help.
      Use encouraging language and celebrate health milestones.`,
    chw: `The user is a Community Health Worker (CHPS).
      You can use more technical language. Focus on patient assessment,
      risk identification, referral decisions, and visit planning.
      Help them prioritize their caseload.`,
    nurse: `The user is a Nurse or Doctor. Use professional medical terminology.
      Focus on clinical assessments, treatment protocols, and evidence-based recommendations.
      Reference Ghana Health Service guidelines.`,
    admin: `The user is a health administrator.
      Focus on system usage, data analytics, and health program management.`,
  };
  return contexts[role] || contexts.mother;
}

/**
 * Perform a quick risk assessment based on symptoms.
 */
export async function assessRisk(patientContext, symptoms) {
  const prompt = `Based on the following patient context and symptoms, provide a risk assessment.

PATIENT CONTEXT:
${JSON.stringify(patientContext, null, 2)}

REPORTED SYMPTOMS:
${symptoms.join(', ')}

Respond in this exact JSON format:
{
  "risk_level": "low" | "moderate" | "high" | "critical",
  "summary": "Brief assessment summary",
  "recommendations": ["recommendation 1", "recommendation 2"],
  "urgency": "routine" | "soon" | "urgent" | "emergency",
  "refer": true | false}`;

  const response = await chatCompletion([{ role: 'user', content: prompt }], {
    temperature: 0.3,
    userRole: 'chw',
  });

  try {
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
  } catch {
    // Fall back to safe default
  }

  return {
    risk_level: 'moderate',
    summary: 'Unable to fully assess. Please consult a healthcare professional.',
    recommendations: ['Visit your nearest health facility for a proper assessment'],
    urgency: 'soon',
    refer: true,
  };
}

export const isAiConfigured = () => !!OPENROUTER_API_KEY;
